title: "Anna Leung's Website"
theme: minima

description: |
  <a href="mailto:leung.yi.lmu@gmail.com">Email</a> |
  <a href="https://orcid.org/0000-0003-0720-5036" target="_blank">ORCID</a> |
  <a href="https://linkedin.com/in/leungyianna" target="_blank">LinkedIn</a> |
  <a href="https://x.com/leungyianna" target="_blank">Twitter</a>

# Define navigation links
nav_links:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/
  - title: "Blog"
    url: /blog/
