title: "Anna Leung's Website"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

navigation:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/cv/"
  - title: "Publications"
    url: "/publications/"
  - title: "Projects"
    url: "/projects/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Blog"
    url: "/blog/"
