title: "Anna Leung's Website"
remote_theme: "daattali/beautiful-jekyll"

menu:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/cv/"
  - title: "Publications"
    url: "/publications/"
  - title: "Projects"
    url: "/projects/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Blog"
    url: "/blog/"
