title: "Anna Leung's Website"
theme: minima

description: |
  [Email](mailto:leung.yi.lmu@gmail.com) |
  [ORCID](https://orcid.org/0000-0003-0720-5036) |
  [LinkedIn](https://linkedin.com/in/leungyianna) |
  [Twitter](https://x.com/leungyianna)

# Define navigation links
nav_links:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/
  - title: "Blog"
    url: /blog/
