title: "Anna Leung's Website"
theme: minima

# Define navigation links
nav_links:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/
  - title: "Blog"
    url: /blog/
