title: "Anna Leung's Website"
theme: minima

# Define navigation links
nav_links:
  - title: "CV"
    url: /cv/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/

description: |
  Site created by Anna Leung | Email: leung.yi.lmu(at)gmail.com

